version: '2'

services:
  brackets-dev:
    image: registry2.swarm.devfactory.com/devfactory/brackets/brackets-ds:v1
    container_name: brackets-dev
    volumes:
      - ..:/data:Z
    command: bash
    tty: true
    ports:
        - "5005"
    cpu_quota: 200000
    mem_limit: 8G
    privileged: false
    labels:
        - "com.trilogy.company=DevFactory"
        - "com.trilogy.team=Eng.DSImport"
        - "com.trilogy.product=brackets"
        - "com.trilogy.service=bracket"
        - "com.trilogy.stage=dev"
        - "com.trilogy.maintainer.skype=thien@aurea.com"
        - "com.trilogy.maintainer.email=thien@aurea.com"
