FROM devspaces/brackets

LABEL \
    "com.trilogy.product"="Brackets" \
    "com.trilogy.company"="External" \
    "com.trilogy.stage"="dev" \
    "com.trilogy.maintainer.skype"="otaviocx" \
    "com.trilogy.maintainer.email"="otaviocalaca.xavier@aurea.com" \
    "description"="This file generates a docker image containing Node.JS and tools needed to build Brackets project"

WORKDIR /data
